{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "69fee59e_0260765e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 80
      },
      "writtenOn": "2022-12-14T13:16:55Z",
      "side": 1,
      "message": "022-12-14 11:03:02Z [standalone]: CREATE_COMPLETE  Stack CREATE completed successfully\n\n\n Stack standalone/f191b291-c3e1-434b-9820-5f30138a055b CREATE_COMPLETE \n\nand then: \n[WARNING]: Using run_once with the tripleo_free strategy is not currently\n\nsupported. This task will still be executed for every host in the inventory\n\nlist.\n\nERROR! Unexpected Exception, this is probably a bug: \u0027Task\u0027 object has no attribute \u0027_valid_attrs\u0027\n",
      "revId": "3e0b89aa5a8136ee0a61d653ab7a1c7fb8270361",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    }
  ]
}