{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "840e4ab5_e796395a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 128
      },
      "writtenOn": "2023-04-25T07:02:15Z",
      "side": 1,
      "message": "tooz update has been reverted in https://review.opendev.org/c/openstack/requirements/+/881329 because of incompatibility with python 3.8. Even though RDO is using python 3.9, we are also reverting to follow u-c as close as possible.",
      "revId": "aa5a789b50affe46bf9e0fce39a8f82343de3247",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    }
  ]
}